### ISSUE TITLE
Document the known issue regarding the typedef

### ISSUE THREAD

**Issue by keerthivarman-nageshwaran** [solitontech/SLL-Drona#18]
The test fails as the typedef that gets into exe will not be the same as the typedef that gets into PPL built for testing.

Current solution: typedefs are disconnected during the exe and PPL build

**Comment by Sairam0496** [comment]
This occurred when we had Assert - "Equal (Value and Type)". Now, we have changed to Assert - "Equal (Value)" as this is widely needed. So, typedefs work without issues and needn't be disconnected. The issue can be closed.
