### ISSUE TITLE
Drona examples are not available in the search result of the LV example finder

### ISSUE THREAD

**Issue by keerthivarman-nageshwaran** [solitontech/SLL-Drona#43]

**Comment by kavin1730** [comment]
Examples can be listed down in LV example finder by creating a bin3 file and place it in corresponding location.

In "LabVIEW>>Tools>>Prepare Examples VIs for NI Example Finder" bin3 file can be created.

![image](https://github.com/solitontech/SLL-Drona/assets/135618969/0847be19-593b-4f50-b8d9-8caea049117e)


Navigate to "\LabVIEW\examples\exbins\" and save the bin3 file.

Restart LabVIEW to display example VI's in LabVIEW Find Examples.
